// Export ABIs and addresses from the compiled JSON files in this folder.
// These JSON files are generated by Hardhat and copied into the frontend/abis
// folder by the repo's build/deploy workflow.

import LogiTokenJson from './LogiToken.json';
import ShipmentRegistryJson from './ShipmentRegistry.json';
import EscrowMilestoneJson from './EscrowMilestone.json';

export const LogiTokenABI = {
  address: LogiTokenJson.address || '',
  abi: LogiTokenJson.abi || [],
};

export const ShipmentRegistryABI = {
  address: ShipmentRegistryJson.address || '',
  abi: ShipmentRegistryJson.abi || [],
};

export const EscrowMilestoneABI = {
  address: EscrowMilestoneJson.address || '',
  abi: EscrowMilestoneJson.abi || [],
};

// If you redeploy contracts, ensure these JSON files are updated (they already
// contain `address` and `abi`). Vite will pick up changes after restart.
